### PR TITLE
Updating Azure Functions version from 3 to 4 - node version.

### PR DESCRIPTION
**Pull request by glaucia86**
## Purpose

 @toolboc asked us to update the Azure functions version from 3 to 4. So, I would like to ask for @yorek and @anthonychu to review it!

## Does this introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ x ] Feature
[ x ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by toolboc** [comment]
@glaucia86, in order to run locally without the storage emulator installed (in addition to running Node v16, we will need to update `localsettings.json.template` to:

```
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=false;",
        "AzureWebJobsSecretStorageType": "files",
        "FUNCTIONS_WORKER_RUNTIME": "node",
        "WEBSITE_NODE_DEFAULT_VERSION": "~16",
        "RealTimeFeedUrl": "https://s3.amazonaws.com/kcm-alerts-realtime-prod/vehiclepositions_enhanced.json",
        "LogicAppUrl": "",
        "AzureSQLConnectionString": "mssql://cloudadmin:[password]@[server-name].database.windows.net/bus-db?encrypt=true"           
    }
```

**Comment by toolboc** [comment]
@glaucia86,  we will want to update mssql dependency in `packages.json` from "^6.3.1" to "^8.1.2" for forward compatibility and to accomodate the following in the underlying '[tedious](https://tediousjs.github.io/tedious/getting-started.html#:~:text=Tedious%20will%20use%20an%20encrypted%20connection%20by%20default,explicitly%20set%20%7Bencrypt%3A%20false%7D%20within%20the%20options%20object.)' package:

*Tedious will use an encrypted connection by default from v6.0.0 onwards. If you have an earlier version, and require encryption or use Windows Azure, you must set {encrypt: true} within the options object. Similarly, if you need an unencrypted connection, you must explicitly set {encrypt: false} within the options object.*

**Comment by toolboc** [comment]
@glaucia86, finally we need to update the `env` section of the Github action in `nodefunction.template.yml` to use latest node LTS version 16:

With these changes I was able to verify that your PR can run locally and deploy to Azure as specified in the associated module.

```
env:
  AZURE_FUNCTIONAPP_NAME: catch-the-bus-node   # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-function/node'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x, 14.x, 16.x)
```

**Comment by toolboc** [comment]
FYI, there is an associated PR to learn-pr that addresses necessary documentation updates to accomodate this PR.  I will merge this pending updates and successful merge here!

https://github.com/MicrosoftDocs/learn-pr/pull/28414

**Comment by glaucia86** [comment]
> "AzureSQLConnectionString": "Server=tcp:<server-name>.database.windows.net,1433;Database=bus-db;User ID=cloudadmin;Password=<Password>;Encrypt=true;Connection Timeout=30;"

Resolved it! ;)

**Comment by glaucia86** [comment]
> ^8.1.2

Done!

**Comment by glaucia86** [comment]
> @glaucia86, finally we need to update the `env` section of the Github action in `nodefunction.template.yml` to use latest node LTS version 16:
> 
> With these changes I was able to verify that your PR can run locally and deploy to Azure and run as expected as specified in the associated [Learn module](https://docs.microsoft.com/en-us/learn/modules/deploy-backend-apis).
> 
> ```
> env:
>   AZURE_FUNCTIONAPP_NAME: catch-the-bus-node   # set this to your application's name
>   AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-function/node'      # set this to the path to your web app project, defaults to the repository root
>   NODE_VERSION: '16.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x, 14.x, 16.x)
> ```

Done!

**Pull request merged**
